#!/bin/bash

testsetup_storage_getstoragelist() {
    testsetup_simple
    local result=$?

    # save the storage names in a global array
    local line
    for line in "${testoutput[@]}"; do
        storage=$(sed -rn 's/\"storage\": \"(.*)\",/\1/p' <<< "$line")
        [[ -n $storage ]] && storages+=($storage)
    done

    # sort the array
    local oldifs=$IFS
    IFS=$'\n' storages=($(sort <<< "${storages[*]}")) IFS=$oldifs

    return $result
}

testsetup_storage_findstorage() {
    testsetup_loop_storage 'Finding all detected storages'
}

testsetup_storage_check() {
    testsetup_loop_storage 'Checking all detected storages'

}

testsetup_storage_getinfo() {
    testsetup_loop_storage 'Getting info on all detected storages'
}


